// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gradient_gkwreg
arma::vec gradient_gkwreg(const arma::vec& theta_concat, const arma::vec& y, const Rcpp::List& X_list, const std::string& family, const Rcpp::List& link_list, const Rcpp::IntegerVector& param_indices, const Rcpp::IntegerVector& n_coefs);
RcppExport SEXP _gkwreg2_gradient_gkwreg(SEXP theta_concatSEXP, SEXP ySEXP, SEXP X_listSEXP, SEXP familySEXP, SEXP link_listSEXP, SEXP param_indicesSEXP, SEXP n_coefsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_concat(theta_concatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type link_list(link_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type param_indices(param_indicesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type n_coefs(n_coefsSEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_gkwreg(theta_concat, y, X_list, family, link_list, param_indices, n_coefs));
    return rcpp_result_gen;
END_RCPP
}
// gradient_numerical
arma::vec gradient_numerical(const arma::vec& theta_concat, const arma::vec& y, const Rcpp::List& X_list, const std::string& family, const Rcpp::List& link_list, const Rcpp::IntegerVector& param_indices, const Rcpp::IntegerVector& n_coefs, double eps);
RcppExport SEXP _gkwreg2_gradient_numerical(SEXP theta_concatSEXP, SEXP ySEXP, SEXP X_listSEXP, SEXP familySEXP, SEXP link_listSEXP, SEXP param_indicesSEXP, SEXP n_coefsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_concat(theta_concatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type link_list(link_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type param_indices(param_indicesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type n_coefs(n_coefsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_numerical(theta_concat, y, X_list, family, link_list, param_indices, n_coefs, eps));
    return rcpp_result_gen;
END_RCPP
}
// link_log
double link_log(double theta);
RcppExport SEXP _gkwreg2_link_log(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(link_log(theta));
    return rcpp_result_gen;
END_RCPP
}
// invlink_log
double invlink_log(double eta);
RcppExport SEXP _gkwreg2_invlink_log(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(invlink_log(eta));
    return rcpp_result_gen;
END_RCPP
}
// dinvlink_log
double dinvlink_log(double eta);
RcppExport SEXP _gkwreg2_dinvlink_log(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvlink_log(eta));
    return rcpp_result_gen;
END_RCPP
}
// link_sqrt
double link_sqrt(double theta);
RcppExport SEXP _gkwreg2_link_sqrt(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(link_sqrt(theta));
    return rcpp_result_gen;
END_RCPP
}
// invlink_sqrt
double invlink_sqrt(double eta);
RcppExport SEXP _gkwreg2_invlink_sqrt(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(invlink_sqrt(eta));
    return rcpp_result_gen;
END_RCPP
}
// dinvlink_sqrt
double dinvlink_sqrt(double eta);
RcppExport SEXP _gkwreg2_dinvlink_sqrt(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvlink_sqrt(eta));
    return rcpp_result_gen;
END_RCPP
}
// link_inverse
double link_inverse(double theta);
RcppExport SEXP _gkwreg2_link_inverse(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(link_inverse(theta));
    return rcpp_result_gen;
END_RCPP
}
// invlink_inverse
double invlink_inverse(double eta);
RcppExport SEXP _gkwreg2_invlink_inverse(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(invlink_inverse(eta));
    return rcpp_result_gen;
END_RCPP
}
// dinvlink_inverse
double dinvlink_inverse(double eta);
RcppExport SEXP _gkwreg2_dinvlink_inverse(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvlink_inverse(eta));
    return rcpp_result_gen;
END_RCPP
}
// link_identity
double link_identity(double theta);
RcppExport SEXP _gkwreg2_link_identity(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(link_identity(theta));
    return rcpp_result_gen;
END_RCPP
}
// invlink_identity
double invlink_identity(double eta);
RcppExport SEXP _gkwreg2_invlink_identity(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(invlink_identity(eta));
    return rcpp_result_gen;
END_RCPP
}
// dinvlink_identity
double dinvlink_identity(double eta);
RcppExport SEXP _gkwreg2_dinvlink_identity(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvlink_identity(eta));
    return rcpp_result_gen;
END_RCPP
}
// link_logit
double link_logit(double theta);
RcppExport SEXP _gkwreg2_link_logit(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(link_logit(theta));
    return rcpp_result_gen;
END_RCPP
}
// invlink_logit
double invlink_logit(double eta);
RcppExport SEXP _gkwreg2_invlink_logit(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(invlink_logit(eta));
    return rcpp_result_gen;
END_RCPP
}
// dinvlink_logit
double dinvlink_logit(double eta);
RcppExport SEXP _gkwreg2_dinvlink_logit(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvlink_logit(eta));
    return rcpp_result_gen;
END_RCPP
}
// link_probit
double link_probit(double theta);
RcppExport SEXP _gkwreg2_link_probit(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(link_probit(theta));
    return rcpp_result_gen;
END_RCPP
}
// invlink_probit
double invlink_probit(double eta);
RcppExport SEXP _gkwreg2_invlink_probit(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(invlink_probit(eta));
    return rcpp_result_gen;
END_RCPP
}
// dinvlink_probit
double dinvlink_probit(double eta);
RcppExport SEXP _gkwreg2_dinvlink_probit(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvlink_probit(eta));
    return rcpp_result_gen;
END_RCPP
}
// link_cloglog
double link_cloglog(double theta);
RcppExport SEXP _gkwreg2_link_cloglog(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(link_cloglog(theta));
    return rcpp_result_gen;
END_RCPP
}
// invlink_cloglog
double invlink_cloglog(double eta);
RcppExport SEXP _gkwreg2_invlink_cloglog(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(invlink_cloglog(eta));
    return rcpp_result_gen;
END_RCPP
}
// dinvlink_cloglog
double dinvlink_cloglog(double eta);
RcppExport SEXP _gkwreg2_dinvlink_cloglog(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvlink_cloglog(eta));
    return rcpp_result_gen;
END_RCPP
}
// link_cauchy
double link_cauchy(double theta);
RcppExport SEXP _gkwreg2_link_cauchy(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(link_cauchy(theta));
    return rcpp_result_gen;
END_RCPP
}
// invlink_cauchy
double invlink_cauchy(double eta);
RcppExport SEXP _gkwreg2_invlink_cauchy(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(invlink_cauchy(eta));
    return rcpp_result_gen;
END_RCPP
}
// dinvlink_cauchy
double dinvlink_cauchy(double eta);
RcppExport SEXP _gkwreg2_dinvlink_cauchy(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvlink_cauchy(eta));
    return rcpp_result_gen;
END_RCPP
}
// apply_invlink
arma::vec apply_invlink(const arma::vec& eta, const std::string& link_type);
RcppExport SEXP _gkwreg2_apply_invlink(SEXP etaSEXP, SEXP link_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link_type(link_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_invlink(eta, link_type));
    return rcpp_result_gen;
END_RCPP
}
// apply_dinvlink
arma::vec apply_dinvlink(const arma::vec& eta, const std::string& link_type);
RcppExport SEXP _gkwreg2_apply_dinvlink(SEXP etaSEXP, SEXP link_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link_type(link_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_dinvlink(eta, link_type));
    return rcpp_result_gen;
END_RCPP
}
// apply_link
arma::vec apply_link(const arma::vec& theta, const std::string& link_type);
RcppExport SEXP _gkwreg2_apply_link(SEXP thetaSEXP, SEXP link_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link_type(link_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_link(theta, link_type));
    return rcpp_result_gen;
END_RCPP
}
// objective_gkwreg
double objective_gkwreg(const arma::vec& theta_concat, const arma::vec& y, const Rcpp::List& X_list, const std::string& family, const Rcpp::List& link_list, const Rcpp::IntegerVector& param_indices, const Rcpp::IntegerVector& n_coefs);
RcppExport SEXP _gkwreg2_objective_gkwreg(SEXP theta_concatSEXP, SEXP ySEXP, SEXP X_listSEXP, SEXP familySEXP, SEXP link_listSEXP, SEXP param_indicesSEXP, SEXP n_coefsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_concat(theta_concatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type link_list(link_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type param_indices(param_indicesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type n_coefs(n_coefsSEXP);
    rcpp_result_gen = Rcpp::wrap(objective_gkwreg(theta_concat, y, X_list, family, link_list, param_indices, n_coefs));
    return rcpp_result_gen;
END_RCPP
}
// objective_gkwreg_vec
double objective_gkwreg_vec(const arma::vec& theta_concat, const arma::vec& y, const Rcpp::List& X_list, const std::string& family, const Rcpp::List& link_list, const Rcpp::IntegerVector& param_indices, const Rcpp::IntegerVector& n_coefs);
RcppExport SEXP _gkwreg2_objective_gkwreg_vec(SEXP theta_concatSEXP, SEXP ySEXP, SEXP X_listSEXP, SEXP familySEXP, SEXP link_listSEXP, SEXP param_indicesSEXP, SEXP n_coefsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_concat(theta_concatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type link_list(link_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type param_indices(param_indicesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type n_coefs(n_coefsSEXP);
    rcpp_result_gen = Rcpp::wrap(objective_gkwreg_vec(theta_concat, y, X_list, family, link_list, param_indices, n_coefs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gkwreg2_gradient_gkwreg", (DL_FUNC) &_gkwreg2_gradient_gkwreg, 7},
    {"_gkwreg2_gradient_numerical", (DL_FUNC) &_gkwreg2_gradient_numerical, 8},
    {"_gkwreg2_link_log", (DL_FUNC) &_gkwreg2_link_log, 1},
    {"_gkwreg2_invlink_log", (DL_FUNC) &_gkwreg2_invlink_log, 1},
    {"_gkwreg2_dinvlink_log", (DL_FUNC) &_gkwreg2_dinvlink_log, 1},
    {"_gkwreg2_link_sqrt", (DL_FUNC) &_gkwreg2_link_sqrt, 1},
    {"_gkwreg2_invlink_sqrt", (DL_FUNC) &_gkwreg2_invlink_sqrt, 1},
    {"_gkwreg2_dinvlink_sqrt", (DL_FUNC) &_gkwreg2_dinvlink_sqrt, 1},
    {"_gkwreg2_link_inverse", (DL_FUNC) &_gkwreg2_link_inverse, 1},
    {"_gkwreg2_invlink_inverse", (DL_FUNC) &_gkwreg2_invlink_inverse, 1},
    {"_gkwreg2_dinvlink_inverse", (DL_FUNC) &_gkwreg2_dinvlink_inverse, 1},
    {"_gkwreg2_link_identity", (DL_FUNC) &_gkwreg2_link_identity, 1},
    {"_gkwreg2_invlink_identity", (DL_FUNC) &_gkwreg2_invlink_identity, 1},
    {"_gkwreg2_dinvlink_identity", (DL_FUNC) &_gkwreg2_dinvlink_identity, 1},
    {"_gkwreg2_link_logit", (DL_FUNC) &_gkwreg2_link_logit, 1},
    {"_gkwreg2_invlink_logit", (DL_FUNC) &_gkwreg2_invlink_logit, 1},
    {"_gkwreg2_dinvlink_logit", (DL_FUNC) &_gkwreg2_dinvlink_logit, 1},
    {"_gkwreg2_link_probit", (DL_FUNC) &_gkwreg2_link_probit, 1},
    {"_gkwreg2_invlink_probit", (DL_FUNC) &_gkwreg2_invlink_probit, 1},
    {"_gkwreg2_dinvlink_probit", (DL_FUNC) &_gkwreg2_dinvlink_probit, 1},
    {"_gkwreg2_link_cloglog", (DL_FUNC) &_gkwreg2_link_cloglog, 1},
    {"_gkwreg2_invlink_cloglog", (DL_FUNC) &_gkwreg2_invlink_cloglog, 1},
    {"_gkwreg2_dinvlink_cloglog", (DL_FUNC) &_gkwreg2_dinvlink_cloglog, 1},
    {"_gkwreg2_link_cauchy", (DL_FUNC) &_gkwreg2_link_cauchy, 1},
    {"_gkwreg2_invlink_cauchy", (DL_FUNC) &_gkwreg2_invlink_cauchy, 1},
    {"_gkwreg2_dinvlink_cauchy", (DL_FUNC) &_gkwreg2_dinvlink_cauchy, 1},
    {"_gkwreg2_apply_invlink", (DL_FUNC) &_gkwreg2_apply_invlink, 2},
    {"_gkwreg2_apply_dinvlink", (DL_FUNC) &_gkwreg2_apply_dinvlink, 2},
    {"_gkwreg2_apply_link", (DL_FUNC) &_gkwreg2_apply_link, 2},
    {"_gkwreg2_objective_gkwreg", (DL_FUNC) &_gkwreg2_objective_gkwreg, 7},
    {"_gkwreg2_objective_gkwreg_vec", (DL_FUNC) &_gkwreg2_objective_gkwreg_vec, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_gkwreg2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
