# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute gradient of negative log-likelihood for gkwreg2
#'
#' Uses chain rule: ∂ℓ/∂β_p = Xᵀ_p × (∂ℓ/∂θ_p × ∂θ_p/∂η_p)
#'
#' @param theta_concat Concatenated regression coefficients
#' @param y Response vector (values in (0,1))
#' @param X_list List of design matrices (one per parameter)
#' @param family Distribution family name
#' @param link_list Named list of link functions per parameter
#' @param param_indices Integer vector with start indices for each parameter
#' @param n_coefs Integer vector with number of coefficients per parameter
#'
#' @return Gradient vector (same length as theta_concat)
#'
#' @keywords internal
gradient_gkwreg <- function(theta_concat, y, X_list, family, link_list, param_indices, n_coefs) {
    .Call(`_gkwreg2_gradient_gkwreg`, theta_concat, y, X_list, family, link_list, param_indices, n_coefs)
}

#' Compute numerical gradient via central differences
#'
#' @param theta_concat Concatenated regression coefficients
#' @param y Response vector
#' @param X_list List of design matrices
#' @param family Distribution family
#' @param link_list Named list of link functions
#' @param param_indices Start indices
#' @param n_coefs Number of coefficients per parameter
#' @param eps Step size for finite differences
#'
#' @return Numerical gradient vector
#'
#' @keywords internal
gradient_numerical <- function(theta_concat, y, X_list, family, link_list, param_indices, n_coefs, eps = 1e-6) {
    .Call(`_gkwreg2_gradient_numerical`, theta_concat, y, X_list, family, link_list, param_indices, n_coefs, eps)
}

link_log <- function(theta) {
    .Call(`_gkwreg2_link_log`, theta)
}

invlink_log <- function(eta) {
    .Call(`_gkwreg2_invlink_log`, eta)
}

dinvlink_log <- function(eta) {
    .Call(`_gkwreg2_dinvlink_log`, eta)
}

link_sqrt <- function(theta) {
    .Call(`_gkwreg2_link_sqrt`, theta)
}

invlink_sqrt <- function(eta) {
    .Call(`_gkwreg2_invlink_sqrt`, eta)
}

dinvlink_sqrt <- function(eta) {
    .Call(`_gkwreg2_dinvlink_sqrt`, eta)
}

link_inverse <- function(theta) {
    .Call(`_gkwreg2_link_inverse`, theta)
}

invlink_inverse <- function(eta) {
    .Call(`_gkwreg2_invlink_inverse`, eta)
}

dinvlink_inverse <- function(eta) {
    .Call(`_gkwreg2_dinvlink_inverse`, eta)
}

link_identity <- function(theta) {
    .Call(`_gkwreg2_link_identity`, theta)
}

invlink_identity <- function(eta) {
    .Call(`_gkwreg2_invlink_identity`, eta)
}

dinvlink_identity <- function(eta) {
    .Call(`_gkwreg2_dinvlink_identity`, eta)
}

link_logit <- function(theta) {
    .Call(`_gkwreg2_link_logit`, theta)
}

invlink_logit <- function(eta) {
    .Call(`_gkwreg2_invlink_logit`, eta)
}

dinvlink_logit <- function(eta) {
    .Call(`_gkwreg2_dinvlink_logit`, eta)
}

link_probit <- function(theta) {
    .Call(`_gkwreg2_link_probit`, theta)
}

invlink_probit <- function(eta) {
    .Call(`_gkwreg2_invlink_probit`, eta)
}

dinvlink_probit <- function(eta) {
    .Call(`_gkwreg2_dinvlink_probit`, eta)
}

link_cloglog <- function(theta) {
    .Call(`_gkwreg2_link_cloglog`, theta)
}

invlink_cloglog <- function(eta) {
    .Call(`_gkwreg2_invlink_cloglog`, eta)
}

dinvlink_cloglog <- function(eta) {
    .Call(`_gkwreg2_dinvlink_cloglog`, eta)
}

link_cauchy <- function(theta) {
    .Call(`_gkwreg2_link_cauchy`, theta)
}

invlink_cauchy <- function(eta) {
    .Call(`_gkwreg2_invlink_cauchy`, eta)
}

dinvlink_cauchy <- function(eta) {
    .Call(`_gkwreg2_dinvlink_cauchy`, eta)
}

apply_invlink <- function(eta, link_type) {
    .Call(`_gkwreg2_apply_invlink`, eta, link_type)
}

apply_dinvlink <- function(eta, link_type) {
    .Call(`_gkwreg2_apply_dinvlink`, eta, link_type)
}

apply_link <- function(theta, link_type) {
    .Call(`_gkwreg2_apply_link`, theta, link_type)
}

#' Compute negative log-likelihood for gkwreg2
#'
#' @param theta_concat Concatenated regression coefficients
#' @param y Response vector (values in (0,1))
#' @param X_list List of design matrices (one per parameter)
#' @param family Distribution family name
#' @param link_list Named list of link functions per parameter
#' @param param_indices Integer vector with start indices for each parameter
#' @param n_coefs Integer vector with number of coefficients per parameter
#'
#' @return Negative log-likelihood value
#'
#' @keywords internal
objective_gkwreg <- function(theta_concat, y, X_list, family, link_list, param_indices, n_coefs) {
    .Call(`_gkwreg2_objective_gkwreg`, theta_concat, y, X_list, family, link_list, param_indices, n_coefs)
}

#' Compute negative log-likelihood using vectorized gkwdist calls
#'
#' @param theta_concat Concatenated regression coefficients
#' @param y Response vector
#' @param X_list List of design matrices
#' @param family Distribution family
#' @param link_list Named list of link functions
#' @param param_indices Start indices
#' @param n_coefs Number of coefficients per parameter
#'
#' @return Negative log-likelihood value
#'
#' @keywords internal
objective_gkwreg_vec <- function(theta_concat, y, X_list, family, link_list, param_indices, n_coefs) {
    .Call(`_gkwreg2_objective_gkwreg_vec`, theta_concat, y, X_list, family, link_list, param_indices, n_coefs)
}

